# Generated by Django 4.1.7 on 2023-03-30 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='prod_id',
        ),
    ]
