# Generated by Django 4.1.7 on 2023-03-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=50)),
                ('acc_no', models.BigIntegerField()),
                ('ifsc', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('acc_holder_name', models.CharField(max_length=50)),
                ('ph_num', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='seller/')),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'seller',
            },
        ),
    ]
