# Generated by Django 4.1.7 on 2023-03-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
